### ISSUE TITLE
Using cli: Python virtualenv to conda environments.

### ISSUE THREAD

**Issue by msuzen** [eth-cscs/openstack#2]
`virtualenv` is a bit problematic in some platforms. If  [anaconda](https://anaconda.org/anaconda/python) distribution of python is used. `conda` environment can be created as follows:
`conda create -n openstack_cli python=2.7 anaconda`

**Comment by naevtamarkus** [comment]
Thanks a lot for the info! 
We have Docker as an option when virtualenv is not available... but I guess it's also a matter of taste. The openstack-client is not really hard to install and there is plenty of documentation around there on how to do it depending on the platform.
The important piece of code in the repo is the source bash script. Does it work well if you install the client with anaconda?

**Comment by msuzen** [comment]
On the contrary it was helpful to have a helper script. Thank you. Some comments

*  `openstack` has some bug on python 2.7, [here](https://bugs.launchpad.net/horizon/+bug/1431508) so I tried on 3.6, your bash script worked there.  
* If you have time/funding to develop a testing for the script that would be great. with a dummy account publicly available. (via Travis CI, so if something is broken one could detect). 
* Documenting Python versions and `swift` usage environment variable would be great. As some user may not be that fluent in using UNIX shell.

**Comment by naevtamarkus** [comment]
The link you sent is about the horizon gui, not the CLI... I tested with python 2.7 and works well, but I'm pretty sure there must be some corner cases (there always are with python!) 
I don't quite understand what you mean by `swift` environment variable... are you referring to the shell alias? If so, that's said in the script's output... but if the user does not know what an alias is, I understand it might be confusing. In any case, the classic 'openstack object ...' commands work well without the alias.

**Comment by msuzen** [comment]
Yes, the link is mistaken. Error message was coming from other dependencies. I think I had some issue with the Anaconda env.

No, not the alias. These are the environment variables, I meant [*]. These are specific parameters for `cscs`, users might want to configure for other products that could connect to storage.  

[*]
```
export OS_USERNAME=$uservar
export OS_PASSWORD=$passvar
export OS_IDENTITY_API_VERSION=3
export OS_AUTH_URL=https://pollux.cscs.ch:13000/v3
export OS_IDENTITY_PROVIDER=cscskc
export OS_IDENTITY_PROVIDER_URL=https://kc.cscs.ch/auth/realms/cscs/protocol/saml/
export OS_PROTOCOL=mapped
export OS_INTERFACE=public
```

**Comment by naevtamarkus** [comment]
I see. For the standard swift client, the wrapper (alias) we provide works better than the environment variables. For other clients, each requires a different configuration (one cannot possible document all clients, and each client comes with its documentation)... and many are outdated anyway. 
Openstack's direction is to unify the standard clients through the 'openstack' command, using the variables you paster above, which is great... but it's not complete yet: that's why we created the swift alias. Eventually, that one will have to go as well.
What other swift client are you referring to?

**Comment by msuzen** [comment]
[swiftclient-gui](https://github.com/FredHutch/swiftclient-gui)
